### ISSUE TITLE
SD card connections as per Arduino

### ISSUE THREAD

**Issue by raghavendrahassy** [ExploreEmbedded/Hornbill-Base-Board#4]
Make the SD card connections as per below image.
![sd card connections for arduino](https://cloud.githubusercontent.com/assets/12540595/25301141/e0010842-273c-11e7-8d26-0d2738cf82da.PNG)

**Comment by sharanago** [comment]
Connection done as per image, Please verify the schematic once before sending for Fabrication.
![image](https://cloud.githubusercontent.com/assets/8638394/25470567/65065e64-2b40-11e7-937e-7e08f929cbf2.png)
